DROP DATABASE IF EXISTS userDB;
CREATE DATABASE userDB;
USE userDB;
SET NAMES utf8;

CREATE TABLE IF NOT EXISTS users(
	user_id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	passw VARCHAR(15) NOT NULL);
	
CREATE TABLE IF NOT EXISTS ingredients(
	ingr_id INT AUTO_INCREMENT PRIMARY KEY,
	ingr_name VARCHAR(50) NOT NULL UNIQUE);
    
CREATE TABLE IF NOT EXISTS preferences(
	value INT DEFAULT 0,
    user_ref INT NOT NULL REFERENCES users.user_id ON DELETE CASCADE ON UPDATE CASCADE,
    ingr_ref INT NOT NULL,
    FOREIGN KEY(user_ref) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(ingr_ref) REFERENCES ingredients(ingr_id) ON DELETE CASCADE ON UPDATE CASCADE);
    
INSERT INTO users (username,passw) VALUES ('admin', 'admin');
